//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntentCADEMR.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntentCADEMREntities : DbContext
    {
        public IntentCADEMREntities()
            : base("name=IntentCADEMREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserStatu> UserStatus { get; set; }
        public virtual DbSet<EmailCorrespondence> EmailCorrespondences { get; set; }
        public virtual DbSet<UserProvince> UserProvinces { get; set; }
        public virtual DbSet<UserTypeLookUp> UserTypeLookUps { get; set; }
        public virtual DbSet<PayeeInfo> PayeeInfoes { get; set; }
        public virtual DbSet<RegistrationInfo> RegistrationInfoes { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<UserRegistration> UserRegistrations { get; set; }
    }
}
