//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntentCADEMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationInfo
    {
        public int id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ClinicName { get; set; }
        public string MailingAddress { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Gender { get; set; }
        public string MedicalSpecialty { get; set; }
        public string MedicalSpecialtyOther { get; set; }
        public string Practice { get; set; }
        public string PracticeOther { get; set; }
        public string PracticeYears { get; set; }
        public Nullable<int> PatientNumbers { get; set; }
        public string ProportionPAD { get; set; }
        public string ProportionCD { get; set; }
        public string ProportionDM { get; set; }
        public string ProportionRD { get; set; }
        public string ProportionHF { get; set; }
        public string ProportionCurrentSmoker { get; set; }
        public string FamiliarCOMPASSTrial { get; set; }
        public Nullable<bool> SomeCAD_PAD { get; set; }
        public Nullable<bool> SomeCAD_2RiskFactors { get; set; }
        public Nullable<bool> MostCAD_PAD { get; set; }
        public Nullable<bool> MostCAD_2RiskFactors { get; set; }
        public Nullable<bool> NoImpact { get; set; }
        public string ASA { get; set; }
        public string Statin { get; set; }
        public string ACEI { get; set; }
        public string OAA { get; set; }
        public string Rivaroxaban { get; set; }
        public Nullable<bool> LackEvidenceBasedGuidelines { get; set; }
        public Nullable<bool> LackApplicabilityGuidelines { get; set; }
        public Nullable<bool> LackTime { get; set; }
        public Nullable<bool> OrganizationalInstitutional { get; set; }
        public Nullable<bool> ReimbursementFinancial { get; set; }
        public Nullable<bool> PatientAdherence { get; set; }
        public Nullable<bool> TreatmentAdverseEvents { get; set; }
        public Nullable<bool> NoneAbove { get; set; }
        public string EducationalPracticalSolutions { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
